config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'activities#index'

  get 'dashboard', to: 'pages#dashboard', as: :dashboard

  resources :activities do
    resources :players, only: :create
    resources :chatrooms, only: [:show] do
      resources :messages, only: :create
    end
  end

  resources :chatrooms, only: [:index]

  get 'users/me', to: 'users#me', as: :me

  resources :users, only: %i[show edit update]

  resources :players, only: :destroy
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :user
  belongs_to :sport
  has_many :players, :dependent => :delete_all
  has_many :users, through: :players


  validates :title, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true
  validates :player_limit, presence: true, numericality: true
  validates :location, presence: true
  validates :skill_level, inclusion: { in: %w[Beginner Intermediate Pro] }
  validates :description, presence: true, length: { maximum: 120 }
  validates :sport, presence: true
  validates :user, presence: true


  def is_owner?(user)
    self.user == user
  end

  def is_player?(user)
    self.users.include?(user)
  end

  def add_player(user, invitation = false)
    Player.create!(user: user, activity: self, invitation: invitation)
  end

  def add_chatroom
    Chatroom.create(activity: self)
  end

  def my_chatroom
    Chatroom.where(activity: self).first
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  belongs_to :activity
  has_many :messages, dependent: :destroy

  def self.connect_all_chatrooms
    Activity.all.each { |activity| activity.add_chatroom if !activity.my_chatroom}
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :activity
  belongs_to :user
end

app/models/sport.rb
class Sport < ApplicationRecord
  has_many :activities
  validates :name, inclusion: { in: %w[Basketball Tennis Football Running Volleyball Yoga] }, uniqueness: true
end

app/models/sport_user.rb
class SportUser < ApplicationRecord
  belongs_to :user
  belongs_to :sport

  validates :skill_level, inclusion: { in: %w[Beginner Intermediate Pro] }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :photo
  has_one_attached :background_photo

  has_many :players
  has_many :activities

  #has_many :activities_joined, through: :players, source: :activities
  has_many :sport_users
  has_many :sports, through: :sport_users

  validates :username, presence: true, uniqueness: true, length: { minimum: 3, maximum: 12 }
  validates :gender, presence: true, inclusion: { in: %w[Male Female] }

  def activities_joined
    Player.where(user: self).map{ |player| player.activity }
  end

  def my_activity_chatrooms
    self.activities_joined.map { |activity| activity.my_chatroom }
  end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController

  def index
    if params[:query].present?
      sql_query = " \
        activities.location ILIKE :query \
        OR sports.name ILIKE :query \
        "
      @activities = Activity.joins(:sport).where(sql_query, query: "%#{params[:query]}%")
    else
      @activities = Activity.all
    end
  end

  def show
    @activity = Activity.find(params[:id])
    @player = Player.find_by(activity: @activity, user: current_user)
  end

  def new
    @activity = Activity.new
  end

  def create
    @activity = Activity.new(activities_params)
    @activity.user = current_user
    if @activity.save
      @activity.add_player(current_user, true)
      @activity.add_chatroom
      redirect_to activity_path(@activity)
    else
      render :new
    end
  end

  def edit
    @activity = Activity.find(params[:id])
  end

  def update
    @activity = Activity.find(params[:id])
    @activity.update(activities_params)
    redirect_to activity_path(@activity)
  end

  def destroy
    @activity = Activity.find(params[:id])
    @activity.destroy
    redirect_to activities_path
  end

  private

  def activities_params
    params.require(:activity).permit(:title, :start_time, :end_time, :player_limit, :location, :skill_level, :description, :sport_id)
  end

  def set_activity
    @activity = Activity.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  def show
    @activity = Activity.find(params[:activity_id])
    @chatroom = Chatroom.find(params[:id])
    @message = Message.new
  end

  def index
    @chatrooms = current_user.my_activity_chatrooms
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @chatroom = Chatroom.find(params[:chatroom_id])
    @message = Message.new(message_params)
    @message.chatroom = @chatroom
    @message.user = current_user
    if @message.save
      ChatroomChannel.broadcast_to(
        @chatroom,
        render_to_string(partial: "message", locals: { message: @message })
      )
      redirect_to activity_chatroom_path(@chatroom.activity, @chatroom, anchor: "message-#{@message.id}")
    else
      render "chatrooms/show"
    end
  end

  def message_params
    params.require(:message).permit(:content)
  end
end

app/controllers/pages_controller.rb
require 'date'

class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home], :raise => false

  def home
  end

  def dashboard
    @activities = current_user.activities_joined
    if params[:query]
      if params[:query] == "joined"
        @activities = @activities.select{|activity|activity.start_time >= Time.now}
      end
       if params[:query] == "past"
        @activities = @activities.select{|activity|activity.start_time < Time.now}
      end
      if params[:query] == "created"
        @activities = current_user.activities
      end
    end
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_activity, only: :create

  def create
    @player = Player.new
    @player.activity = @activity
    @player.user = current_user
    if @player.save
      redirect_to activity_path(@activity), notice: 'You have joined'
    else
      render 'activities/show'
    end
  end

  def destroy
    @player = Player.find(params[:id])
    @player.destroy
    redirect_to activities_path, notice: 'You have left the activity'
  end

  private

  def set_activity
    @activity = Activity.find(params[:activity_id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update]

  def show
  end

  def me
    @user = current_user
    render :show
  end

  def edit
  end

  def update
    if params[:user][:sport_ids].size >= 2
      @user.sport_users.each {|su| su.destroy! }
      params[:user][:sport_ids].each { |spo_id| SportUser.create(user: @user, sport: Sport.find(spo_id), skill_level: 'Intermediate') if spo_id != ""}
    end
    @user.update(user_params)
    redirect_to me_path(@user)
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:description, :skill_level)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/activities/_card.html.erb
    <div class="card-activity-index">

<% unless activity.players.count == activity.player_limit %>
  <%= link_to(activity_path(activity)) do %>
      <%= image_tag "#{activity.sport.name.downcase}.jpg", class: 'card-activity-image' %>
      <div class="card-activity-index-infos border-bottom">
        <div>
          <h2 class='mb-2'><%= activity.title %></h2>
          <p class='mb-1'><%= activity.location %></p>
          <p class='mb-1'><%= activity.start_time.strftime("%A, %B %-d, %H:%M") %></p>
        </div>
        <a class="card-activity-index-btn btn btn-sport" href="#"><%= activity.sport.name %></a>
      </div>

      <div class="card-activity-index-players">
        <div class="mr-8 card-activity-index-host">
        <% if activity.user.photo.attached? %>
          <%= link_to(user_path(activity.user)) do%><%=cl_image_tag(activity.user.photo.key, crop: :fill, class: "avatar-large") %><% end %>
        <% else %>
          <%= link_to(user_path(activity.user)) do%><%= image_tag "default_avatar.png", crop: :fill, class:"avatar-large" %><% end %>
        <% end %>
        </div>
        <div class="card-activity-index-player">
          <% activity.users.reject{ |us| us == activity.user }.take(3).map do |u| %>
            <% if u.photo.attached? %>
              <%= link_to(user_path(u)) do%><%= cl_image_tag(u.photo.key, crop: :fill, class: "avatar") %><% end %>
            <% else %>
              <%= link_to(user_path(u)) do%><%= image_tag "default_avatar.png", crop: :fill, class:"avatar" %><% end %>
            <% end %>
          <% end %>
          <div class='card-activity-index-ct'>
            <% if activity.players.count > 4  %>
              <span>+<%= activity.players.count - 4 %> </span>
            <% end %>
          </div>
        </div>
        <div class='card-activity-index-nd'>
          <p><em><strong><%= pluralize(activity.player_limit - activity.players.count, 'spot')%> left </strong></em></p>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/activities/_form.html.erb
<%= simple_form_for activity do |f| %>
  <%= f.input :start_time, as: :string, required: true, input_html: {class: "datepicker"} %>
  <%= f.input :end_time, as: :string, required: true, input_html: {class: "datepicker"} %>
  <%= f.input :title, label: "Activity's name", placeholder: 'My Activity', input_html: { maxlength: 25 } %>
  <%= f.input :location, input_html: {id:'activity_location'} %>
  <%= f.association :sport %>
  <div class="row">
    <div class="col">
      <%= f.input :skill_level, collection: %w[Beginner Intermediate Pro] %>
    </div>
    <div class="col">
      <label for="rangePlayer">Player limit</label>&nbsp;<output name="playerOutputName" id="playerOutputId">10</output>
      <br>
      <input type="range" name="activity[player_limit]" id="playerInputId" value="10" min="1" max="21" oninput="playerOutputId.value = playerInputId.value">

    </div>
  </div>
  <%= f.input :description, required: true, input_html: { maxlength: 120 } %>
  <div class="form-group d-flex justify-content-end">
    <% if activity.id %>
    <input class="btn btn-primary" type="submit" value="Save Acitivty" name="commit">
    <% else %>
     <input class="btn btn-primary" type="submit" value="Create Acitivty" name="commit">
     <% end %>
  </div>
<% end %>
<%= javascript_pack_tag 'init_auto_complete' %>
<%= javascript_pack_tag 'flatpickr' %>

app/views/activities/edit.html.erb
<div class="container-edit">
  <h1> Edit your Activity </h1>
  <%= render "form", activity: @activity %>
</div>

app/views/activities/index.html.erb
<div class="container">
  <div class="searchbar">
    <%= form_tag activities_path, method: :get do %>
      <div class='form-search'>
        <%= text_field_tag :query,
          params[:query],
          class: 'form-control',
          placeholder: '🔍 Search by sport or location'
        %>
          <!-- <%= submit_tag "", class: "" %>-->
    <% end  %>
      </div>
  </div>
    <div class="cards-container">
    <% @activities.each do |activity| %>
        <%= render 'activities/card', activity: activity %>
    <% end %>
  </div>
</div>

app/views/activities/new.html.erb
<div class="container-edit">
  <h1> Create an Activity </h1>
  <%= render "form", activity: @activity %>
</div>

app/views/activities/show.html.erb
<div class='container-show mb-10'>

  <div class="card-activity-show border-bottom">
    <p class="back-arrow">
      <%= link_to :back do %>
      <i class="arrow left"></i>
      <% end %>
    </p>
    <%= image_tag "#{@activity.sport.name.downcase}.jpg", class: 'card-activity-image' %>


    <div class="card-activity-show-infos">

      <div>
        <div class="show-header">
        <% if @activity.is_owner?(current_user) %>
        <h2 class='show-title'><%= @activity.title %></h2>
        <%= link_to activity_path(@activity), method: :delete, data: {confirm: 'Are you sure?'} do %><i class="fas fa-trash"></i><% end %>
        <% else %>
        <h2 class='show-title'><%= @activity.title %></h2>
        <% end %>
        </div>
        <p class='show-paragraph'><%= '🗓'  %> <%= @activity.start_time.strftime("%A, %B %-d, %H:%M -") %> <%= @activity.end_time.strftime("%H:%M")%> </p>
        <p class='show-paragraph'><%= '📍' %><%= @activity.location %></p>
        <p class='show-paragraph'><%= @activity.description %></p>
      </div>
      <a class="card-activity-show-btn btn" href="#"><%= @activity.sport.name %> </a>

      <div class="card-activity-show-frame">
        <% if @activity.is_owner?(current_user) %>
        <div class="card-activity-show-players">
          <p> <strong>Limit: </strong> </p>
          <p> <strong> <%= @activity.players.count %>  </strong> playing </p>
          <p>  <strong> <%= @activity.player_limit - @activity.players.count %> </strong>  needed </p>
        </div>
        <div class="divider-vertical"></div>
        <div class="card-activity-show-skill">
          <p> <strong> Skill Level: </strong> </p>
          <p> <%= @activity.skill_level%></p>
        </div>
        <% else %>
        <div class="card-activity-show-players">
          <p> <strong>Limit: </strong> </p>
          <p> <strong> <%= @activity.players.count %>  </strong> playing </p>
          <p>  <strong> <%= @activity.player_limit - @activity.players.count %> </strong>  needed </p>
        </div>
        <div class="divider-vertical-avatar"></div>
        <div class="card-activity-show-skill">
          <p> <strong> Skill Level: </strong> </p>
          <p> <%= @activity.skill_level%></p>
        </div>
        <div class="divider-vertical-avatar"></div>
        <div class="card-activity-show-host-photo">
          <p> <strong>Host: </strong> </p>
          <% if @activity.user.photo.attached? %>
          <%= link_to(user_path(@activity.user)) do%>
          <%=cl_image_tag(@activity.user.photo.key, crop: :fill, class: "avatar-showpage") %>
          <% end %>
          <% else %>
          <%= link_to(user_path(@activity.user)) do%>
          <%= image_tag "default_avatar.png", crop: :fill, class:"avatar-large" %>
          <% end %>
          <% end %>
          <% end %>
        </div>
      </div>


      <% if @activity.is_owner?(current_user) %>
        <div class= "show-btn-action">
          <%= link_to edit_activity_path(@activity), class: "btn-edit" do %>Edit <i class="fas fa-edit"></i><% end %>
        </div>
      <% elsif @activity.is_player?(current_user) %>
        <div class= "show-btn-action">
          <%= link_to "Leave", player_path(@player), method: :delete, remote: true,  class: "btn-leave"%>
        </div>
      <% else %>
        <div class= "show-btn-action">
          <%= link_to "Join", activity_players_path(@activity), method: :post, remote: true, class: "btn-join"%>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FreshSport</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/pages/_dashboard_activities.html.erb
<% if @video.try(:any?) %>
  <div class="activities-cards">
    <% activities.sort_by(&:start_time).each do |activity| %>
      <%= render 'activity_card', activity: activity %>
      <p></p>
    <% end %>
  </div>

<% elsif params.include?(:query) %>
 <div class="dashbaord-cards">
  <% if params[:query] == 'joined' %>
    <div class="no-activities">You haven't joined any activities yet!</div>
  <% elsif params[:query] == 'created' %>
    <div class="no-activities">You haven't created any activities yet</div>
  <% elsif params[:query] == 'past' %>
    <div class="no-activities">You have no past activities</div>
  <% else %>
    <div class="no-activities">You have no activities</div>
  <% end %>
  <% else %> <%# no activities, but no query given %>
  <div class="no-activities">You have no activities</div>
<% end %>
</div>

app/views/pages/dashboard.html.erb
<%= render "shared/navbar" %>
<div class="container-dash">
  <br>
  <div class="current-games">
      <%= link_to "Joined", dashboard_path(query:"joined"), class:"#{params[:query] == "joined" || params[:query].nil? ? 'btn-dashboard' : 'btn-dash-game'}" %>
      <%= link_to "Created", dashboard_path(query:"created"), class:"#{params[:query] == "created" ? 'btn-dashboard' : 'btn-dash-game'}" %>
      <%= link_to "Past", dashboard_path(query:"past"), class:"#{params[:query] == "past" ? 'btn-dashboard' : 'btn-dash-game'}" %>
  </div>
  <br>
  <%= render "dashboard_activities", activities: @activities %>
</div>

app/views/pages/home.html.erb
<div class="homepage-container">
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://res.cloudinary.com/diavcbwzh/image/upload/v1602158504/fresh_1_rvl4xt.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", activities_path(@activities), class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "New Activity", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Dashboard", dashboard_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://res.cloudinary.com/diavcbwzh/image/upload/v1602158504/fresh_1_rvl4xt.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>